<?php
require_once __DIR__ . "/public_home_i18n.php";

function public_home_legal_notice_catalog()
{
    static $catalog = null;
    if($catalog !== null) {
        return $catalog;
    }

    $catalog = array(
        "es" => <<<'HTML'
<div class="legal-notice-copy" style="text-align: justify;">
<p><strong>Responsable:</strong><br />Red Phone Events, S.L.<br />C/Pelai, 32 4t2a 08001 Barcelona</p>
<p><strong>Contacto:</strong><br />E-mail info@nekomailing.com</p>
<p><strong>Registro:</strong><br />Tomo: 45996 Folio: 506322 Inscripción: 1 Fecha de inscripción: 30 de junio de 2017<br />Número de identificación fiscal: B67030817</p>
<p><strong>2. USUARIOS</strong><br />El acceso y/o uso de este portal de Neko Mailing (Red Phone Events, S.L.) atribuye la condición de usuario, que acepta, desde dicho acceso y/o uso, las Condiciones Generales de Uso aquí reflejadas. Estas condiciones serán de aplicación con independencia de las Condiciones Generales de Contratación que, en su caso, resulten de obligado cumplimiento.</p>
<p><strong>3. USO DEL PORTAL</strong><br />www.nekomailing.com proporciona acceso a informaciones, servicios, programas o datos en Internet pertenecientes a Neko Mailing (Red Phone Events, S.L.) o a sus licenciantes. El usuario asume la responsabilidad del uso del portal. Dicha responsabilidad se extiende al registro necesario para acceder a determinados servicios o contenidos.</p>
<p>En dicho registro el usuario será responsable de aportar información veraz y lícita. Como consecuencia de este registro, al usuario se le puede proporcionar una contraseña de la que será responsable, comprometiéndose a hacer un uso diligente y confidencial de la misma. El usuario se compromete a hacer un uso adecuado de los contenidos y servicios que Neko Mailing pueda ofrecer a través del portal y, con carácter enunciativo pero no limitativo, a no emplearlos para actividades ilícitas, ilegales o contrarias a la buena fe y al orden público; difundir contenidos o propaganda de carácter racista, xenófobo, pornográfico-ilegal, de apología del terrorismo o atentatorio contra los derechos humanos; provocar daños en los sistemas físicos y lógicos de Neko Mailing, de sus proveedores o de terceras personas; introducir o difundir virus informáticos u otros sistemas susceptibles de provocar dichos daños; o intentar acceder y, en su caso, utilizar las cuentas de correo electrónico de otros usuarios y modificar o manipular sus mensajes.</p>
<p>Neko Mailing se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren el respeto a la dignidad de la persona, que sean discriminatorios, xenófobos, racistas, pornográficos, que atenten contra la juventud o la infancia, el orden o la seguridad pública o que, a su juicio, no resulten adecuados para su publicación. En cualquier caso, Neko Mailing no será responsable de las opiniones vertidas por los usuarios a través de los foros, chats u otras herramientas de participación.</p>
<p><strong>4. PROTECCIÓN DE DATOS</strong><br />Neko Mailing cumple con la normativa vigente en materia de protección de datos personales y vela por garantizar un correcto uso y tratamiento de los datos personales del usuario. Para ello, junto a cada formulario de recogida de datos personales, en los servicios que el usuario pueda solicitar, se informará al usuario de la existencia y aceptación de las condiciones particulares del tratamiento de sus datos en cada caso, de la responsabilidad del fichero creado, de la dirección del responsable, de la posibilidad de ejercer sus derechos de acceso, rectificación, supresión, limitación u oposición, de la finalidad del tratamiento y de las comunicaciones de datos a terceros, en su caso.</p>
<p>Asimismo, Neko Mailing informa que cumple la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico, y solicitará el consentimiento del usuario para el tratamiento de su correo electrónico con fines comerciales cuando resulte necesario.</p>
<p><strong>5. PROPIEDAD INTELECTUAL E INDUSTRIAL</strong><br />Neko Mailing, por sí o como cesionaria, es titular de todos los derechos de propiedad intelectual e industrial de su página web, así como de los elementos contenidos en la misma, entre otros: imágenes, sonido, audio, vídeo, software, textos, marcas, logotipos, combinaciones de colores, estructura, diseño, selección de materiales y programas necesarios para su funcionamiento, acceso y uso.</p>
<p>Todos los derechos reservados. Queda expresamente prohibida la reproducción, distribución y comunicación pública, incluida su modalidad de puesta a disposición, de la totalidad o parte de los contenidos de esta página web, con fines comerciales, en cualquier soporte y por cualquier medio técnico, sin la autorización de Neko Mailing. El usuario se compromete a respetar los derechos de propiedad intelectual e industrial titularidad de Neko Mailing. Podrá visualizar los elementos del portal, imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte físico siempre que sea, única y exclusivamente, para su uso personal y privado. El usuario deberá abstenerse de suprimir, alterar, eludir o manipular cualquier dispositivo de protección o sistema de seguridad instalado en las páginas de Neko Mailing.</p>
<p><strong>6. EXCLUSIÓN DE GARANTÍAS Y RESPONSABILIDAD</strong><br />Neko Mailing no se hace responsable, en ningún caso, de los daños y perjuicios de cualquier naturaleza que pudieran ocasionar, a título enunciativo: errores u omisiones en los contenidos, falta de disponibilidad del portal o transmisión de virus o programas maliciosos o lesivos en los contenidos, pese a haber adoptado todas las medidas tecnológicas necesarias para evitarlo.</p>
<p><strong>7. MODIFICACIONES</strong><br />Neko Mailing se reserva el derecho de efectuar, sin previo aviso, las modificaciones que considere oportunas en su portal, pudiendo cambiar, suprimir o añadir tanto los contenidos y servicios que se presten a través del mismo como la forma en la que estos aparezcan presentados o localizados.</p>
<p><strong>8. ENLACES</strong><br />En el caso de que www.nekomailing.com se dispusieran enlaces o hipervínculos hacia otros sitios de Internet, Red Phone Events no ejercerá ningún tipo de control sobre dichos sitios y contenidos. En ningún caso Neko Mailing asumirá responsabilidad alguna por los contenidos de enlaces pertenecientes a sitios web ajenos, ni garantizará la disponibilidad técnica, calidad, fiabilidad, exactitud, amplitud, veracidad, validez o constitucionalidad de cualquier material o información contenida en dichos hipervínculos u otros sitios de Internet.</p>
<p>La inclusión de estas conexiones externas no implicará ningún tipo de asociación, fusión o participación con las entidades conectadas.</p>
<p><strong>9. DERECHO DE EXCLUSIÓN</strong><br />Neko Mailing se reserva el derecho a denegar o retirar el acceso al portal y/o a los servicios ofrecidos, sin necesidad de preaviso, a instancia propia o de un tercero, a aquellos usuarios que incumplan las presentes Condiciones Generales de Uso.</p>
<p><strong>10. GENERALIDADES</strong><br />Neko Mailing perseguirá el incumplimiento de las presentes condiciones, así como cualquier utilización indebida de su portal, ejerciendo todas las acciones civiles y penales que le puedan corresponder en derecho.</p>
<p><strong>11. MODIFICACIÓN DE LAS PRESENTES CONDICIONES Y DURACIÓN</strong><br />Neko Mailing podrá modificar en cualquier momento las condiciones aquí determinadas, siendo debidamente publicadas como aquí aparecen. La vigencia de estas condiciones dependerá de su exposición y estarán vigentes hasta que sean modificadas por otras debidamente publicadas.</p>
<p><strong>12. LEGISLACIÓN APLICABLE Y JURISDICCIÓN</strong><br />La relación entre Neko Mailing (Red Phone Events, S.L.) y el usuario se regirá por la normativa española vigente y cualquier controversia se someterá a los Juzgados y tribunales de la ciudad de Barcelona.</p>
</div>
HTML,
        "ca" => <<<'HTML'
<div class="legal-notice-copy" style="text-align: justify;">
<p><strong>Responsable:</strong><br />Red Phone Events, S.L.<br />C/Pelai, 32 4t2a 08001 Barcelona</p>
<p><strong>Contacte:</strong><br />E-mail info@nekomailing.com</p>
<p><strong>Registre:</strong><br />Tom: 45996 Foli: 506322 Inscripció: 1 Data d'inscripció: 30 de juny de 2017<br />Número d'identificació fiscal: B67030817</p>
<p><strong>2. USUARIS</strong><br />L'accés i/o ús d'aquest portal de Neko Mailing (Red Phone Events, S.L.) atribueix la condició d'usuari, que accepta, des d'aquest accés i/o ús, les Condicions Generals d'Ús aquí reflectides. Aquestes condicions s'aplicaran amb independència de les Condicions Generals de Contractació que, si escau, siguin d'obligat compliment.</p>
<p><strong>3. ÚS DEL PORTAL</strong><br />www.nekomailing.com proporciona accés a informacions, serveis, programes o dades a Internet pertanyents a Neko Mailing (Red Phone Events, S.L.) o als seus llicenciants. L'usuari assumeix la responsabilitat de l'ús del portal. Aquesta responsabilitat s'estén al registre necessari per accedir a determinats serveis o continguts.</p>
<p>En aquest registre l'usuari serà responsable d'aportar informació veraç i lícita. Com a conseqüència d'aquest registre, a l'usuari se li pot facilitar una contrasenya de la qual serà responsable, comprometent-se a fer-ne un ús diligent i confidencial. L'usuari es compromet a fer un ús adequat dels continguts i serveis que Neko Mailing pugui oferir a través del portal i, amb caràcter enunciatiu però no limitatiu, a no emprar-los per a activitats il·lícites, il·legals o contràries a la bona fe i a l'ordre públic; difondre continguts o propaganda de caràcter racista, xenòfob, pornogràfic-il·legal, d'apologia del terrorisme o atemptatori contra els drets humans; provocar danys als sistemes físics i lògics de Neko Mailing, dels seus proveïdors o de terceres persones; introduir o difondre virus informàtics o altres sistemes susceptibles de provocar aquests danys; o intentar accedir i, si escau, utilitzar els comptes de correu electrònic d'altres usuaris i modificar o manipular els seus missatges.</p>
<p>Neko Mailing es reserva el dret de retirar tots aquells comentaris i aportacions que vulnerin el respecte a la dignitat de la persona, que siguin discriminatoris, xenòfobs, racistes, pornogràfics, que atemptin contra la joventut o la infància, l'ordre o la seguretat pública o que, al seu judici, no resultin adequats per a la seva publicació. En qualsevol cas, Neko Mailing no serà responsable de les opinions abocades pels usuaris a través dels fòrums, xats o altres eines de participació.</p>
<p><strong>4. PROTECCIÓ DE DADES</strong><br />Neko Mailing compleix la normativa vigent en matèria de protecció de dades personals i vetlla per garantir un ús i tractament correctes de les dades personals de l'usuari. Per fer-ho, juntament amb cada formulari de recollida de dades personals, en els serveis que l'usuari pugui sol·licitar, s'informarà l'usuari de l'existència i acceptació de les condicions particulars del tractament de les seves dades en cada cas, de la responsabilitat del fitxer creat, de l'adreça del responsable, de la possibilitat d'exercir els seus drets d'accés, rectificació, supressió, limitació o oposició, de la finalitat del tractament i de les comunicacions de dades a tercers, si escau.</p>
<p>Així mateix, Neko Mailing informa que compleix la Llei 34/2002, d'11 de juliol, de Serveis de la Societat de la Informació i del Comerç Electrònic, i sol·licitarà el consentiment de l'usuari per al tractament del seu correu electrònic amb finalitats comercials quan sigui necessari.</p>
<p><strong>5. PROPIETAT INTEL·LECTUAL I INDUSTRIAL</strong><br />Neko Mailing, per si mateixa o com a cessionària, és titular de tots els drets de propietat intel·lectual i industrial de la seva pàgina web, així com dels elements que hi conté, entre d'altres: imatges, so, àudio, vídeo, programari, textos, marques, logotips, combinacions de colors, estructura, disseny, selecció de materials i programes necessaris per al seu funcionament, accés i ús.</p>
<p>Tots els drets reservats. Queda expressament prohibida la reproducció, distribució i comunicació pública, inclosa la seva modalitat de posada a disposició, de la totalitat o part dels continguts d'aquesta pàgina web, amb finalitats comercials, en qualsevol suport i per qualsevol mitjà tècnic, sense l'autorització de Neko Mailing. L'usuari es compromet a respectar els drets de propietat intel·lectual i industrial titularitat de Neko Mailing. Podrà visualitzar els elements del portal, imprimir-los, copiar-los i emmagatzemar-los al disc dur del seu ordinador o en qualsevol altre suport físic sempre que sigui única i exclusivament per al seu ús personal i privat. L'usuari s'haurà d'abstenir d'eliminar, alterar, eludir o manipular qualsevol dispositiu de protecció o sistema de seguretat instal·lat a les pàgines de Neko Mailing.</p>
<p><strong>6. EXCLUSIÓ DE GARANTIES I RESPONSABILITAT</strong><br />Neko Mailing no es fa responsable, en cap cas, dels danys i perjudicis de qualsevol naturalesa que es puguin ocasionar, a títol enunciatiu: errors o omissions en els continguts, manca de disponibilitat del portal o transmissió de virus o programes maliciosos o lesius en els continguts, malgrat haver adoptat totes les mesures tecnològiques necessàries per evitar-ho.</p>
<p><strong>7. MODIFICACIONS</strong><br />Neko Mailing es reserva el dret d'efectuar, sense avís previ, les modificacions que consideri oportunes al seu portal, i pot canviar, suprimir o afegir tant els continguts i serveis que s'hi prestin com la manera en què aquests apareguin presentats o localitzats.</p>
<p><strong>8. ENLLAÇOS</strong><br />En el cas que a www.nekomailing.com hi hagi enllaços o hipervincles cap a altres llocs d'Internet, Red Phone Events no exercirà cap mena de control sobre aquests llocs i continguts. En cap cas Neko Mailing assumirà cap responsabilitat pels continguts d'enllaços pertanyents a llocs web aliens, ni garantirà la disponibilitat tècnica, qualitat, fiabilitat, exactitud, amplitud, veracitat, validesa o constitucionalitat de qualsevol material o informació continguda en aquests hipervincles o altres llocs d'Internet.</p>
<p>La inclusió d'aquestes connexions externes no implicarà cap mena d'associació, fusió o participació amb les entitats connectades.</p>
<p><strong>9. DRET D'EXCLUSIÓ</strong><br />Neko Mailing es reserva el dret a denegar o retirar l'accés al portal i/o als serveis oferts, sense necessitat de preavís, a instància pròpia o d'un tercer, a aquells usuaris que incompleixin aquestes Condicions Generals d'Ús.</p>
<p><strong>10. GENERALITATS</strong><br />Neko Mailing perseguirà l'incompliment de les presents condicions, així com qualsevol utilització indeguda del seu portal, exercint totes les accions civils i penals que li puguin correspondre en dret.</p>
<p><strong>11. MODIFICACIÓ D'AQUESTES CONDICIONS I DURADA</strong><br />Neko Mailing podrà modificar en qualsevol moment les condicions aquí determinades, que seran degudament publicades tal com apareixen aquí. La vigència d'aquestes condicions dependrà de la seva exposició i estaran vigents fins que siguin modificades per unes altres degudament publicades.</p>
<p><strong>12. LEGISLACIÓ APLICABLE I JURISDICCIÓ</strong><br />La relació entre Neko Mailing (Red Phone Events, S.L.) i l'usuari es regirà per la normativa espanyola vigent i qualsevol controvèrsia se sotmetrà als Jutjats i tribunals de la ciutat de Barcelona.</p>
</div>
HTML,
        "en" => <<<'HTML'
<div class="legal-notice-copy" style="text-align: justify;">
<p><strong>Responsible party:</strong><br />Red Phone Events, S.L.<br />C/Pelai, 32 4t2a 08001 Barcelona</p>
<p><strong>Contact:</strong><br />E-mail info@nekomailing.com</p>
<p><strong>Registration:</strong><br />Volume: 45996 Folio: 506322 Registration: 1 Registration date: June 30, 2017<br />Tax identification number: B67030817</p>
<p><strong>2. USERS</strong><br />Access to and/or use of this Neko Mailing portal (Red Phone Events, S.L.) grants the status of user, who accepts, from such access and/or use, the General Conditions of Use set out here. These conditions shall apply regardless of any General Conditions of Contracting that may be mandatory in each case.</p>
<p><strong>3. USE OF THE PORTAL</strong><br />www.nekomailing.com provides access to information, services, programs or data on the Internet belonging to Neko Mailing (Red Phone Events, S.L.) or its licensors. The user assumes responsibility for the use of the portal. This responsibility extends to any registration required to access certain services or content.</p>
<p>In such registration, the user shall be responsible for providing truthful and lawful information. As a result of such registration, the user may be provided with a password for which they will be responsible, undertaking to make diligent and confidential use of it. The user undertakes to make appropriate use of the content and services that Neko Mailing may offer through the portal and, by way of example but not limitation, not to use them for unlawful, illegal or bad-faith activities contrary to public order; to disseminate racist, xenophobic, illegal pornographic content, terrorism advocacy or content that violates human rights; to cause damage to the physical and logical systems of Neko Mailing, its suppliers or third parties; to introduce or spread computer viruses or any other systems capable of causing such damage; or to attempt to access and, where appropriate, use the email accounts of other users and modify or manipulate their messages.</p>
<p>Neko Mailing reserves the right to remove any comments or contributions that violate respect for the dignity of the person, are discriminatory, xenophobic, racist, pornographic, threaten youth or children, public order or safety, or that, in its judgment, are not suitable for publication. In any case, Neko Mailing shall not be responsible for opinions expressed by users through forums, chats or other participation tools.</p>
<p><strong>4. DATA PROTECTION</strong><br />Neko Mailing complies with current personal data protection regulations and strives to ensure the proper use and processing of users' personal data. To this end, together with each personal data collection form, in the services the user may request, the user will be informed of the existence and acceptance of the specific conditions governing the processing of their data in each case, the responsibility for the created file, the address of the controller, the possibility of exercising rights of access, rectification, erasure, restriction or objection, the purpose of the processing and, where applicable, data communications to third parties.</p>
<p>Likewise, Neko Mailing states that it complies with Law 34/2002 of July 11 on Information Society Services and Electronic Commerce, and will request the user's consent for the processing of their email address for commercial purposes whenever required.</p>
<p><strong>5. INTELLECTUAL AND INDUSTRIAL PROPERTY</strong><br />Neko Mailing, either in its own right or as assignee, is the owner of all intellectual and industrial property rights to its website, as well as to the elements contained therein, including but not limited to images, sound, audio, video, software, texts, trademarks, logos, color combinations, structure, design, selection of materials and computer programs required for its operation, access and use.</p>
<p>All rights reserved. The reproduction, distribution and public communication, including making available, of all or part of the contents of this website for commercial purposes, on any medium and by any technical means, is expressly prohibited without the authorization of Neko Mailing. The user undertakes to respect the intellectual and industrial property rights owned by Neko Mailing. The user may view the elements of the portal and even print, copy and store them on the hard drive of their computer or on any other physical medium provided that this is solely and exclusively for their personal and private use. The user must refrain from deleting, altering, circumventing or manipulating any protection device or security system installed on Neko Mailing pages.</p>
<p><strong>6. DISCLAIMER OF WARRANTIES AND LIABILITY</strong><br />Neko Mailing shall under no circumstances be liable for damages of any kind that may arise, including but not limited to errors or omissions in the contents, lack of availability of the portal or the transmission of viruses or malicious or harmful programs in the contents, despite having adopted all necessary technological measures to prevent this.</p>
<p><strong>7. MODIFICATIONS</strong><br />Neko Mailing reserves the right to make, without prior notice, any modifications it deems appropriate to its portal, and may change, remove or add both the content and services provided through it, as well as the way in which they are presented or located.</p>
<p><strong>8. LINKS</strong><br />If www.nekomailing.com includes links or hyperlinks to other Internet sites, Red Phone Events shall not exercise any control over such sites and content. Under no circumstances shall Neko Mailing assume any responsibility for the content of any link belonging to a third-party website, nor guarantee the technical availability, quality, reliability, accuracy, breadth, truthfulness, validity or constitutionality of any material or information contained in such hyperlinks or other Internet sites.</p>
<p>The inclusion of such external links shall not imply any type of association, merger or participation with the connected entities.</p>
<p><strong>9. RIGHT OF EXCLUSION</strong><br />Neko Mailing reserves the right to deny or withdraw access to the portal and/or the services offered, without prior notice, at its own request or at the request of a third party, from users who fail to comply with these General Conditions of Use.</p>
<p><strong>10. GENERAL PROVISIONS</strong><br />Neko Mailing will pursue breaches of these conditions as well as any improper use of its portal by exercising all civil and criminal actions to which it may be entitled by law.</p>
<p><strong>11. MODIFICATION OF THESE CONDITIONS AND DURATION</strong><br />Neko Mailing may modify the conditions set out herein at any time, duly publishing them as they appear here. The validity of these conditions will depend on their publication and they shall remain in force until duly replaced by others.</p>
<p><strong>12. APPLICABLE LAW AND JURISDICTION</strong><br />The relationship between Neko Mailing (Red Phone Events, S.L.) and the user shall be governed by current Spanish law, and any dispute shall be submitted to the Courts and Tribunals of the city of Barcelona.</p>
</div>
HTML,
        "pt" => <<<'HTML'
<div class="legal-notice-copy" style="text-align: justify;">
<p><strong>Responsável:</strong><br />Red Phone Events, S.L.<br />C/Pelai, 32 4t2a 08001 Barcelona</p>
<p><strong>Contacto:</strong><br />E-mail info@nekomailing.com</p>
<p><strong>Registo:</strong><br />Tomo: 45996 Fólio: 506322 Inscrição: 1 Data de inscrição: 30 de junho de 2017<br />Número de identificação fiscal: B67030817</p>
<p><strong>2. UTILIZADORES</strong><br />O acesso e/ou utilização deste portal da Neko Mailing (Red Phone Events, S.L.) atribui a condição de utilizador, que aceita, a partir desse acesso e/ou utilização, as Condições Gerais de Utilização aqui refletidas. Estas condições aplicar-se-ão independentemente das Condições Gerais de Contratação que, se for caso disso, sejam de cumprimento obrigatório.</p>
<p><strong>3. UTILIZAÇÃO DO PORTAL</strong><br />www.nekomailing.com disponibiliza acesso a informações, serviços, programas ou dados na Internet pertencentes à Neko Mailing (Red Phone Events, S.L.) ou aos seus licenciantes. O utilizador assume a responsabilidade pela utilização do portal. Essa responsabilidade estende-se ao registo necessário para aceder a determinados serviços ou conteúdos.</p>
<p>Nesse registo, o utilizador será responsável por fornecer informação verdadeira e lícita. Como consequência desse registo, poderá ser-lhe fornecida uma palavra-passe da qual será responsável, comprometendo-se a fazer um uso diligente e confidencial da mesma. O utilizador compromete-se a fazer uma utilização adequada dos conteúdos e serviços que a Neko Mailing possa oferecer através do portal e, a título exemplificativo mas não limitativo, a não os utilizar para atividades ilícitas, ilegais ou contrárias à boa-fé e à ordem pública; difundir conteúdos ou propaganda de caráter racista, xenófobo, pornográfico-ilegal, de apologia do terrorismo ou atentatórios contra os direitos humanos; causar danos nos sistemas físicos e lógicos da Neko Mailing, dos seus fornecedores ou de terceiros; introduzir ou difundir vírus informáticos ou quaisquer outros sistemas suscetíveis de provocar esses danos; ou tentar aceder e, se for caso disso, utilizar contas de correio eletrónico de outros utilizadores e modificar ou manipular as suas mensagens.</p>
<p>A Neko Mailing reserva-se o direito de retirar todos os comentários e contributos que violem o respeito pela dignidade da pessoa, que sejam discriminatórios, xenófobos, racistas, pornográficos, que atentem contra a juventude ou a infância, a ordem ou a segurança pública ou que, no seu entender, não sejam adequados para publicação. Em qualquer caso, a Neko Mailing não será responsável pelas opiniões emitidas pelos utilizadores através de fóruns, chats ou outras ferramentas de participação.</p>
<p><strong>4. PROTEÇÃO DE DADOS</strong><br />A Neko Mailing cumpre a regulamentação em vigor em matéria de proteção de dados pessoais e vela por garantir uma correta utilização e tratamento dos dados pessoais do utilizador. Para tal, juntamente com cada formulário de recolha de dados pessoais, nos serviços que o utilizador possa solicitar, será informado da existência e aceitação das condições específicas do tratamento dos seus dados em cada caso, da responsabilidade do ficheiro criado, do endereço do responsável, da possibilidade de exercer os seus direitos de acesso, retificação, apagamento, limitação ou oposição, da finalidade do tratamento e das comunicações de dados a terceiros, quando aplicável.</p>
<p>Do mesmo modo, a Neko Mailing informa que cumpre a Lei 34/2002, de 11 de julho, dos Serviços da Sociedade da Informação e do Comércio Eletrónico, e solicitará o consentimento do utilizador para o tratamento do seu correio eletrónico para fins comerciais sempre que tal seja necessário.</p>
<p><strong>5. PROPRIEDADE INTELECTUAL E INDUSTRIAL</strong><br />A Neko Mailing, por si ou como cessionária, é titular de todos os direitos de propriedade intelectual e industrial do seu website, bem como dos elementos nele contidos, incluindo, entre outros, imagens, som, áudio, vídeo, software, textos, marcas, logótipos, combinações de cores, estrutura, design, seleção de materiais e programas necessários para o seu funcionamento, acesso e utilização.</p>
<p>Todos os direitos reservados. Fica expressamente proibida a reprodução, distribuição e comunicação pública, incluindo a colocação à disposição, da totalidade ou de parte dos conteúdos deste website, para fins comerciais, em qualquer suporte e por qualquer meio técnico, sem autorização da Neko Mailing. O utilizador compromete-se a respeitar os direitos de propriedade intelectual e industrial titularidade da Neko Mailing. Poderá visualizar os elementos do portal e até imprimi-los, copiá-los e armazená-los no disco rígido do seu computador ou em qualquer outro suporte físico, desde que isso se destine única e exclusivamente ao seu uso pessoal e privado. O utilizador deverá abster-se de eliminar, alterar, contornar ou manipular qualquer dispositivo de proteção ou sistema de segurança instalado nas páginas da Neko Mailing.</p>
<p><strong>6. EXCLUSÃO DE GARANTIAS E RESPONSABILIDADE</strong><br />A Neko Mailing não se responsabiliza, em nenhum caso, por danos e prejuízos de qualquer natureza que possam ocorrer, a título exemplificativo: erros ou omissões nos conteúdos, falta de disponibilidade do portal ou transmissão de vírus ou programas maliciosos ou nocivos nos conteúdos, apesar de ter adotado todas as medidas tecnológicas necessárias para o evitar.</p>
<p><strong>7. MODIFICAÇÕES</strong><br />A Neko Mailing reserva-se o direito de efetuar, sem aviso prévio, as modificações que considere oportunas no seu portal, podendo alterar, suprimir ou acrescentar tanto os conteúdos e serviços prestados através do mesmo como a forma como estes são apresentados ou localizados.</p>
<p><strong>8. LIGAÇÕES</strong><br />No caso de www.nekomailing.com incluir ligações ou hiperligações para outros sítios da Internet, a Red Phone Events não exercerá qualquer tipo de controlo sobre esses sítios e conteúdos. Em nenhum caso a Neko Mailing assumirá qualquer responsabilidade pelos conteúdos de ligações pertencentes a websites de terceiros, nem garantirá a disponibilidade técnica, qualidade, fiabilidade, exatidão, amplitude, veracidade, validade ou constitucionalidade de qualquer material ou informação contida nessas hiperligações ou noutros sítios da Internet.</p>
<p>A inclusão destas ligações externas não implicará qualquer tipo de associação, fusão ou participação com as entidades ligadas.</p>
<p><strong>9. DIREITO DE EXCLUSÃO</strong><br />A Neko Mailing reserva-se o direito de negar ou retirar o acesso ao portal e/ou aos serviços oferecidos, sem necessidade de aviso prévio, por iniciativa própria ou a pedido de terceiros, aos utilizadores que incumpram as presentes Condições Gerais de Utilização.</p>
<p><strong>10. GENERALIDADES</strong><br />A Neko Mailing perseguirá o incumprimento das presentes condições, assim como qualquer utilização indevida do seu portal, exercendo todas as ações cíveis e penais que lhe possam corresponder por direito.</p>
<p><strong>11. MODIFICAÇÃO DAS PRESENTES CONDIÇÕES E DURAÇÃO</strong><br />A Neko Mailing poderá modificar a qualquer momento as condições aqui estabelecidas, publicando-as devidamente tal como aqui aparecem. A vigência destas condições dependerá da sua publicação e manter-se-ão em vigor até serem devidamente substituídas por outras.</p>
<p><strong>12. LEGISLAÇÃO APLICÁVEL E JURISDIÇÃO</strong><br />A relação entre a Neko Mailing (Red Phone Events, S.L.) e o utilizador reger-se-á pela legislação espanhola em vigor e qualquer litígio será submetido aos Julgados e Tribunais da cidade de Barcelona.</p>
</div>
HTML,
        "fr" => <<<'HTML'
<div class="legal-notice-copy" style="text-align: justify;">
<p><strong>Responsable :</strong><br />Red Phone Events, S.L.<br />C/Pelai, 32 4t2a 08001 Barcelona</p>
<p><strong>Contact :</strong><br />E-mail info@nekomailing.com</p>
<p><strong>Immatriculation :</strong><br />Tome : 45996 Folio : 506322 Inscription : 1 Date d'inscription : 30 juin 2017<br />Numéro d'identification fiscale : B67030817</p>
<p><strong>2. UTILISATEURS</strong><br />L'accès et/ou l'utilisation de ce portail de Neko Mailing (Red Phone Events, S.L.) confère la qualité d'utilisateur, qui accepte, dès cet accès et/ou cette utilisation, les Conditions Générales d'Utilisation exposées ici. Ces conditions s'appliqueront indépendamment des Conditions Générales de Contrat éventuellement applicables.</p>
<p><strong>3. UTILISATION DU PORTAIL</strong><br />www.nekomailing.com donne accès à des informations, services, programmes ou données sur Internet appartenant à Neko Mailing (Red Phone Events, S.L.) ou à ses concédants. L'utilisateur assume la responsabilité de l'utilisation du portail. Cette responsabilité s'étend à l'inscription nécessaire pour accéder à certains services ou contenus.</p>
<p>Lors de cette inscription, l'utilisateur est responsable de fournir des informations véridiques et licites. À la suite de cette inscription, un mot de passe peut être remis à l'utilisateur, qui en sera responsable et s'engage à en faire un usage diligent et confidentiel. L'utilisateur s'engage à faire un usage approprié des contenus et services que Neko Mailing peut proposer via le portail et, à titre indicatif mais non limitatif, à ne pas les utiliser pour des activités illicites, illégales ou contraires à la bonne foi et à l'ordre public ; diffuser des contenus ou propagandes à caractère raciste, xénophobe, pornographique-illicite, faisant l'apologie du terrorisme ou portant atteinte aux droits humains ; provoquer des dommages aux systèmes physiques et logiques de Neko Mailing, de ses fournisseurs ou de tiers ; introduire ou diffuser des virus informatiques ou tout autre système susceptible de causer ces dommages ; ou tenter d'accéder et, le cas échéant, d'utiliser les comptes de courrier électronique d'autres utilisateurs et de modifier ou manipuler leurs messages.</p>
<p>Neko Mailing se réserve le droit de retirer tout commentaire ou contribution portant atteinte au respect de la dignité de la personne, à caractère discriminatoire, xénophobe, raciste, pornographique, portant atteinte à la jeunesse ou à l'enfance, à l'ordre ou à la sécurité publique, ou qui, selon son appréciation, ne seraient pas appropriés à leur publication. En tout état de cause, Neko Mailing ne sera pas responsable des opinions exprimées par les utilisateurs via les forums, chats ou autres outils de participation.</p>
<p><strong>4. PROTECTION DES DONNÉES</strong><br />Neko Mailing respecte la réglementation en vigueur en matière de protection des données personnelles et veille à garantir une utilisation et un traitement corrects des données personnelles de l'utilisateur. À cette fin, avec chaque formulaire de collecte de données personnelles, dans les services que l'utilisateur peut demander, celui-ci sera informé de l'existence et de l'acceptation des conditions particulières du traitement de ses données dans chaque cas, de la responsabilité du fichier créé, de l'adresse du responsable, de la possibilité d'exercer ses droits d'accès, de rectification, d'effacement, de limitation ou d'opposition, de la finalité du traitement et, le cas échéant, des communications de données à des tiers.</p>
<p>De même, Neko Mailing informe qu'elle respecte la Loi 34/2002 du 11 juillet relative aux Services de la Société de l'Information et au Commerce Électronique, et sollicitera le consentement de l'utilisateur pour le traitement de son courrier électronique à des fins commerciales lorsque cela sera nécessaire.</p>
<p><strong>5. PROPRIÉTÉ INTELLECTUELLE ET INDUSTRIELLE</strong><br />Neko Mailing, en propre ou en tant que cessionnaire, est titulaire de tous les droits de propriété intellectuelle et industrielle de son site web, ainsi que des éléments qui y sont contenus, notamment les images, sons, audios, vidéos, logiciels, textes, marques, logos, combinaisons de couleurs, structure, design, sélection des matériaux et programmes nécessaires à son fonctionnement, son accès et son utilisation.</p>
<p>Tous droits réservés. La reproduction, la distribution et la communication publique, y compris la mise à disposition, de tout ou partie des contenus de ce site web, à des fins commerciales, sur tout support et par tout moyen technique, sont expressément interdites sans l'autorisation de Neko Mailing. L'utilisateur s'engage à respecter les droits de propriété intellectuelle et industrielle détenus par Neko Mailing. Il pourra visualiser les éléments du portail et même les imprimer, les copier et les stocker sur le disque dur de son ordinateur ou sur tout autre support physique, à condition que cela soit uniquement et exclusivement pour son usage personnel et privé. L'utilisateur devra s'abstenir de supprimer, altérer, contourner ou manipuler tout dispositif de protection ou système de sécurité installé sur les pages de Neko Mailing.</p>
<p><strong>6. EXCLUSION DE GARANTIES ET DE RESPONSABILITÉ</strong><br />Neko Mailing ne saurait être tenue responsable, en aucun cas, des dommages et préjudices de toute nature pouvant résulter, à titre indicatif, d'erreurs ou omissions dans les contenus, d'un manque de disponibilité du portail ou de la transmission de virus ou programmes malveillants dans les contenus, malgré l'adoption de toutes les mesures technologiques nécessaires pour l'éviter.</p>
<p><strong>7. MODIFICATIONS</strong><br />Neko Mailing se réserve le droit d'effectuer, sans préavis, les modifications qu'elle juge opportunes sur son portail, pouvant changer, supprimer ou ajouter aussi bien les contenus et services fournis que la manière dont ceux-ci sont présentés ou localisés.</p>
<p><strong>8. LIENS</strong><br />Dans le cas où www.nekomailing.com contiendrait des liens ou hyperliens vers d'autres sites Internet, Red Phone Events n'exercera aucun contrôle sur ces sites et contenus. En aucun cas Neko Mailing n'assumera de responsabilité quant aux contenus de liens appartenant à des sites web tiers, ni ne garantira la disponibilité technique, la qualité, la fiabilité, l'exactitude, l'étendue, la véracité, la validité ou la constitutionnalité de tout matériel ou information contenu dans ces hyperliens ou autres sites Internet.</p>
<p>L'inclusion de ces connexions externes n'impliquera aucun type d'association, de fusion ou de participation avec les entités liées.</p>
<p><strong>9. DROIT D'EXCLUSION</strong><br />Neko Mailing se réserve le droit de refuser ou retirer l'accès au portail et/ou aux services proposés, sans préavis, à son initiative ou à la demande d'un tiers, aux utilisateurs qui ne respecteraient pas les présentes Conditions Générales d'Utilisation.</p>
<p><strong>10. GÉNÉRALITÉS</strong><br />Neko Mailing poursuivra tout manquement aux présentes conditions, ainsi que toute utilisation abusive de son portail, en exerçant toutes les actions civiles et pénales qui pourraient lui correspondre en droit.</p>
<p><strong>11. MODIFICATION DES PRÉSENTES CONDITIONS ET DURÉE</strong><br />Neko Mailing pourra modifier à tout moment les conditions ici définies, en les publiant dûment comme elles apparaissent ici. La validité de ces conditions dépendra de leur publication et elles resteront en vigueur jusqu'à leur remplacement dûment publié par d'autres.</p>
<p><strong>12. LÉGISLATION APPLICABLE ET JURIDICTION</strong><br />La relation entre Neko Mailing (Red Phone Events, S.L.) et l'utilisateur sera régie par la législation espagnole en vigueur et tout litige sera soumis aux juridictions de la ville de Barcelone.</p>
</div>
HTML,
    );

    return $catalog;
}

function public_home_legal_notice_html($lang = null)
{
    $lang = public_home_resolve_language($lang);
    $catalog = public_home_legal_notice_catalog();

    if(isset($catalog[$lang]) && trim($catalog[$lang]) !== "") {
        return $catalog[$lang];
    }

    return $catalog["es"];
}
